# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dignity_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobworker',
            old_name='jobs',
            new_name='job',
        ),
    ]
