# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dignity_platform', '0002_auto_20160426_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirers', to='dignity_platform.Job')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_i_want_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
