# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dignity_platform', '0003_jobhirer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseSupporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.1)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_supporting_cause', to='dignity_platform.Cause')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_i_support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
