# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dignity_platform', '0004_causesupporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworker',
            name='price',
            field=models.FloatField(default=15.0),
        ),
    ]
