# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dignity_platform', '0005_jobworker_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='self_support',
            field=models.FloatField(default=0.49),
        ),
    ]
